---@meta

---AceDB-3.0 database object (fields created dynamically by AceDB, so declared here for the language server).
---@class NRSKNUI.AceDB
---@field profile table Active profile settings
---@field global table Account-wide settings
---@field char table Character-specific settings
---@field profiles table<string, table> All stored profiles
---@field defaults table|nil Registered defaults
---@field RegisterCallback fun(target: table, eventName: string, callback: function|string) CallbackHandler registration (dot-call)
---@field UnregisterCallback fun(target: table, eventName: string)
---@field CheckDualSpecState fun(db: NRSKNUI.AceDB)|nil Added by LibDualSpec-1.0
---@field IsDualSpecEnabled fun(self: NRSKNUI.AceDB): boolean Added by LibDualSpec-1.0
---@field SetDualSpecEnabled fun(self: NRSKNUI.AceDB, enabled: boolean) Added by LibDualSpec-1.0
---@field GetDualSpecProfile fun(self: NRSKNUI.AceDB, spec?: number): string Added by LibDualSpec-1.0
---@field SetDualSpecProfile fun(self: NRSKNUI.AceDB, profileName: string, spec?: number) Added by LibDualSpec-1.0
---@field SetProfile fun(self: NRSKNUI.AceDB, name: string)
---@field GetCurrentProfile fun(self: NRSKNUI.AceDB): string
---@field GetProfiles fun(self: NRSKNUI.AceDB, tbl?: table): string[], number
---@field CopyProfile fun(self: NRSKNUI.AceDB, name: string, silent?: boolean)
---@field DeleteProfile fun(self: NRSKNUI.AceDB, name: string, silent?: boolean)
---@field ResetProfile fun(self: NRSKNUI.AceDB, noChildren?: boolean, noCallbacks?: boolean)
---@field ResetDB fun(self: NRSKNUI.AceDB, defaultProfile?: string): NRSKNUI.AceDB
---@field RegisterDefaults fun(self: NRSKNUI.AceDB, defaults: table)
---@field RegisterNamespace fun(self: NRSKNUI.AceDB, name: string, defaults?: table): NRSKNUI.AceDB
---@field GetNamespace fun(self: NRSKNUI.AceDB, name: string, silent?: boolean): NRSKNUI.AceDB|nil
---@field anchorFrameType string e.g 'UIPARENT'
---@field ParentFrame string e.g 'UIParent'
---@field Units table<string, table> Per-unit archetype DB tables (e.g. Units.player, Units.target, Units.party, etc.)

---Base class for anything returned by NRSKNUI:NewModule(...).
---Covers the AceAddon module API plus the AceEvent/AceHook/AceTimer methods
---modules commonly embed, and the custom fields NUI attaches (db, frame).
---@class NRSKNUI.Module
---@field db NRSKNUI.AceDB Per-module namespaced DB (set during init)
---@field frame Frame? Primary display frame, if the module owns one
---@field enabledState boolean
--- AceAddon module methods
---@field GetName fun(self: NRSKNUI.Module): string
---@field IsEnabled fun(self: NRSKNUI.Module): boolean
---@field Enable fun(self: NRSKNUI.Module)
---@field Disable fun(self: NRSKNUI.Module)
---@field SetEnabledState fun(self: NRSKNUI.Module, state: boolean)
--- Lifecycle callbacks (define these on the module itself)
---@field OnInitialize fun(self: NRSKNUI.Module)?
---@field OnEnable fun(self: NRSKNUI.Module)?
---@field OnDisable fun(self: NRSKNUI.Module)?

---@class NRSKNUI.AceEvent: NRSKNUI.Module
---
---Register for a Blizzard event. `callback` may be a function or a method name on self;
---if omitted it defaults to a method named after the event. An optional `arg` is passed
---as the first argument to the callback (the event name follows).
---@field RegisterEvent fun(self: NRSKNUI.AceEvent, event: string, callback?: string|fun(event: string, ...: any), arg?: any)
---
---Unregister a previously registered Blizzard event.
---@field UnregisterEvent fun(self: NRSKNUI.AceEvent, event: string)
---
---Register for a custom AceEvent-internal message. Same callback/arg semantics as RegisterEvent.
---@field RegisterMessage fun(self: NRSKNUI.AceEvent, message: string, callback?: string|fun(message: string, ...: any), arg?: any)
---
---Unregister a previously registered message.
---@field UnregisterMessage fun(self: NRSKNUI.AceEvent, message: string)
---
---Send a message to other addons registered for it, passing along any extra arguments.
---@field SendMessage fun(self: NRSKNUI.AceEvent, message: string, ...: any)
---
---Unregister all Blizzard events currently registered by this object.
---@field UnregisterAllEvents fun(self: NRSKNUI.AceEvent)
---
---Unregister all messages currently registered by this object.
---@field UnregisterAllMessages fun(self: NRSKNUI.AceEvent)


---@class NRSKNUI.AceTimer: NRSKNUI.Module
---
---Schedule a timer to call the given callback after `delay` seconds. Any extra arguments are passed to the callback.
---@field ScheduleTimer fun(self: NRSKNUI.AceTimer, callback: string|fun(), delay: number, ...: any): table
---
---Schedule a repeating timer to call the given callback every `delay` seconds. Any extra arguments are passed to the callback.
---@field ScheduleRepeatingTimer fun(self: NRSKNUI.AceTimer, callback: string|fun(), delay: number, ...: any): table
---
---Cancel a previously scheduled timer. Returns true if the timer was successfully canceled, false if it was not found. If `silent` is true, no error is thrown if the timer is not found.
---@field CancelTimer fun(self: NRSKNUI.AceTimer, id: table, silent?: boolean): boolean

---@class NRSKNUI.AceHook: NRSKNUI.Module
---
---Hooks a method on an object, replacing it with a new function. The original method can be called from the new function using `self.hooks[obj][method]`.
---@field Hook fun(self: NRSKNUI.AceHook, obj: any, method?: any, handler?: any, secure?: boolean)
---
---Rawly hooks a method on an object, replacing it with a new function. The original method can be called from the new function using `self.hooks[obj][method]`.
---@field RawHook fun(self: NRSKNUI.AceHook, obj: any, method?: any, handler?: any, secure?: boolean)
---
---Securely hooks a method on an object, replacing it with a new function. The original method can be called from the new function using `self.hooks[obj][method]`.
---@field SecureHook fun(self: NRSKNUI.AceHook, obj: any, method?: any, handler?: any)
---
---Rawly hooks a script on a frame, replacing it with a new function. The original script can be called from the new function using `self.hooks[frame][script]`.
---@field RawHookScript fun(self: NRSKNUI.AceHook, frame: Frame, script: string, handler?: any)
---
---Securely hooks a script on a frame, replacing it with a new function. The original script can be called from the new function using `self.hooks[frame][script]`.
---@field SecureHookScript fun(self: NRSKNUI.AceHook, frame: Frame, script: string, handler?: any)
---
---Hooks a script on a frame, replacing it with a new function. The original script can be called from the new function using `self.hooks[frame][script]`.
---@field HookScript fun(self: NRSKNUI.AceHook, frame: Frame, script: string, handler?: any)
---
---Unhooks a previously hooked method or script, restoring the original function.
---@field Unhook fun(self: NRSKNUI.AceHook, obj: any, method?: string)
---
---Unhooks all previously hooked methods and scripts, restoring the original functions.
---@field UnhookAll fun(self: NRSKNUI.AceHook)
---
---IsHooked checks if a method or script is currently hooked.
---@field IsHooked fun(self: NRSKNUI.AceHook, obj: any, method?: string): boolean

---@class NRSKNUI.UnitFramesTagSettings
---@field Separator string
---@field UpdateInterval number

---@class NRSKNUI.UnitFramesDB
---@field General table
---@field TagSettings NRSKNUI.UnitFramesTagSettings
---@field Units table<string, table>

---@class UnitFrames : NRSKNUI.Module
---@field db NRSKNUI.UnitFramesDB

---@class NRSKNUI.FocusCastbarTargetNames
---@field Anchor string
---@field XOffset number
---@field YOffset number
---@field FontSize number

---@class NRSKNUI.FocusCastbarTargetMarker
---@field Enabled boolean
---@field Anchor string
---@field Size number
---@field XOffset number
---@field YOffset number

---@class NRSKNUI.FocusCastbarHoldTimer
---@field Enabled boolean
---@field Duration number
---@field InterruptedColor number[]
---@field SuccessColor number[]

---@class NRSKNUI.FocusCastbarKickIndicator
---@field Enabled boolean
---@field TickWidth number
---@field NotReadyColor number[]
---@field TickColor number[]
---@field TickWidth number

---@class NRSKNUI.FocusCastbarGlow
---@field GlowEnabled boolean
---@field GlowType string
---@field GlowColor number[]
---@field GlowLines number
---@field GlowFrequency number
---@field GlowLength number
---@field GlowThickness number
---@field GlowBorder boolean
---@field GlowScale number

---@class NRSKNUI.FocusCastbarDB
---@field Enabled boolean
---@field Width number
---@field Height number
---@field CastColor number[]
---@field NotInterruptibleColor number[]
---@field TextColor number[]
---@field HideNotInterruptible boolean
---@field BackdropColor number[]
---@field BorderColor number[]
---@field TargetNames NRSKNUI.FocusCastbarTargetNames
---@field TargetMarker NRSKNUI.FocusCastbarTargetMarker
---@field HoldTimer NRSKNUI.FocusCastbarHoldTimer
---@field KickIndicator NRSKNUI.FocusCastbarKickIndicator
---@field ImportantGlow NRSKNUI.FocusCastbarGlow
