---@meta

-- Concrete module classes. Methods are defined in each module's own file.

---@class UnitFramesModule : NRSKNUI.ModuleBase, AceEvent-3.0, AceTimer-3.0, AceHook-3.0
---@class RestrictedModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class AuctionHouseFilterModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class AutomationModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class TweaksModule : NRSKNUI.ModuleBase, AceEvent-3.0, AceHook-3.0
---@class XPBarModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class CopyAnythingModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class RecuperateModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class MiscVarsModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class DurabilityModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class BurningRushModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class TooltipsModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class MinimapModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class SkinningModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class GatewayModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class PetTextsModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class PlayerAurasModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class AdvancedDebuffsModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class DefensivesModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class CombatTimerModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class PotionReadyModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class RangeCheckerModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class CombatCrossModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class CombatMessageModule : NRSKNUI.ModuleBase, AceEvent-3.0, AceTimer-3.0
---@class CombatResModule : NRSKNUI.ModuleBase, AceEvent-3.0, AceTimer-3.0
---@class CombatCursorModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class FocusCastbarModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class SpeedModule : NRSKNUI.ModuleBase, AceEvent-3.0
---@class GearUtilityModule : NRSKNUI.ModuleBase, AceEvent-3.0

-- Typed accessors. Overloads dispatch on the literal module name.

---@type NRSKNUI
local NRSKNUI

--- Fetch a registered module by name.
---@overload fun(self: NRSKNUI, name: "CombatTimer", silent?: boolean): CombatTimer
---@overload fun(self: NRSKNUI, name: "Gateway", silent?: boolean): Gateway
---@overload fun(self: NRSKNUI, name: "PotionReady", silent?: boolean): PotionReady
---@overload fun(self: NRSKNUI, name: "RangeChecker", silent?: boolean): RangeChecker
---@overload fun(self: NRSKNUI, name: "Skinning", silent?: boolean): Skinning
---@overload fun(self: NRSKNUI, name: "Tooltips", silent?: boolean): Tooltips
---@overload fun(self: NRSKNUI, name: "Minimap", silent?: boolean): Minimap
---@overload fun(self: NRSKNUI, name: "BurningRush", silent?: boolean): BurningRush
---@overload fun(self: NRSKNUI, name: "AuctionHouseFilter", silent?: boolean): AuctionHouseFilter
---@overload fun(self: NRSKNUI, name: "Automation", silent?: boolean): Automation
---@overload fun(self: NRSKNUI, name: "Tweaks", silent?: boolean): Tweaks
---@overload fun(self: NRSKNUI, name: "XPBar", silent?: boolean): XPBar
---@overload fun(self: NRSKNUI, name: "CopyAnything", silent?: boolean): CopyAnything
---@overload fun(self: NRSKNUI, name: "Recuperate", silent?: boolean): Recuperate
---@overload fun(self: NRSKNUI, name: "MiscVars", silent?: boolean): MiscVars
---@overload fun(self: NRSKNUI, name: "Durability", silent?: boolean): Durability
---@overload fun(self: NRSKNUI, name: "CombatCross", silent?: boolean): CombatCross
---@overload fun(self: NRSKNUI, name: "CombatMessage", silent?: boolean): CombatMessage
---@overload fun(self: NRSKNUI, name: "CombatRes", silent?: boolean): CombatRes
---@overload fun(self: NRSKNUI, name: "Restricted", silent?: boolean): Restricted
---@overload fun(self: NRSKNUI, name: "CursorCircle", silent?: boolean): CursorCircle
---@overload fun(self: NRSKNUI, name: "UnitFrames", silent?: boolean): UnitFrames
---@overload fun(self: NRSKNUI, name: "PlayerAuras", silent?: boolean): PlayerAuras
---@overload fun(self: NRSKNUI, name: "AdvancedDebuffs", silent?: boolean): AdvancedDebuffs
---@overload fun(self: NRSKNUI, name: "Defensives", silent?: boolean): Defensives
---@overload fun(self: NRSKNUI, name: "PetTexts", silent?: boolean): PetTexts
---@overload fun(self: NRSKNUI, name: "FocusCastbar", silent?: boolean): FocusCastbar
---@overload fun(self: NRSKNUI, name: "Speed", silent?: boolean): Speed
---@overload fun(self: NRSKNUI, name: "GearUtility", silent?: boolean): GearUtility
---@param name string
---@param silent? boolean
---@return AceModule
function NRSKNUI:GetModule(name, silent) end

--- Register a new module. Trailing args are embedded library names (e.g. "AceEvent-3.0").
---@overload fun(self: NRSKNUI, name: "CombatTimer", ...: string): CombatTimer
---@overload fun(self: NRSKNUI, name: "Gateway", ...: string): Gateway
---@overload fun(self: NRSKNUI, name: "PotionReady", ...: string): PotionReady
---@overload fun(self: NRSKNUI, name: "RangeChecker", ...: string): RangeChecker
---@overload fun(self: NRSKNUI, name: "Skinning", ...: string): Skinning
---@overload fun(self: NRSKNUI, name: "Tooltips", ...: string): Tooltips
---@overload fun(self: NRSKNUI, name: "Minimap", ...: string): Minimap
---@overload fun(self: NRSKNUI, name: "BurningRush", ...: string): BurningRush
---@overload fun(self: NRSKNUI, name: "AuctionHouseFilter", ...: string): AuctionHouseFilter
---@overload fun(self: NRSKNUI, name: "Automation", ...: string): Automation
---@overload fun(self: NRSKNUI, name: "Tweaks", ...: string): Tweaks
---@overload fun(self: NRSKNUI, name: "XPBar", ...: string): XPBar
---@overload fun(self: NRSKNUI, name: "CopyAnything", ...: string): CopyAnything
---@overload fun(self: NRSKNUI, name: "Recuperate", ...: string): Recuperate
---@overload fun(self: NRSKNUI, name: "MiscVars", ...: string): MiscVars
---@overload fun(self: NRSKNUI, name: "Durability", ...: string): Durability
---@overload fun(self: NRSKNUI, name: "CombatCross", ...: string): CombatCross
---@overload fun(self: NRSKNUI, name: "CombatMessage", ...: string): CombatMessage
---@overload fun(self: NRSKNUI, name: "CombatRes", ...: string): CombatRes
---@overload fun(self: NRSKNUI, name: "Restricted", ...: string): Restricted
---@overload fun(self: NRSKNUI, name: "CursorCircle", ...: string): CursorCircle
---@overload fun(self: NRSKNUI, name: "UnitFrames", ...: string): UnitFrames
---@overload fun(self: NRSKNUI, name: "PlayerAuras", ...: string): PlayerAuras
---@overload fun(self: NRSKNUI, name: "AdvancedDebuffs", ...: string): AdvancedDebuffs
---@overload fun(self: NRSKNUI, name: "Defensives", ...: string): Defensives
---@overload fun(self: NRSKNUI, name: "PetTexts", ...: string): PetTexts
---@overload fun(self: NRSKNUI, name: "FocusCastbar", ...: string): FocusCastbar
---@overload fun(self: NRSKNUI, name: "Speed", ...: string): Speed
---@overload fun(self: NRSKNUI, name: "GearUtility", ...: string): GearUtility
---@param name string
---@param ... string
---@return AceModule
function NRSKNUI:NewModule(name, ...) end