---@meta

-- Concrete module classes. Methods are defined in each module's own file.

---@class CombatTimer : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Gateway : NRSKNUI.Module, NRSKNUI.AceEvent
---@class PotionReady : NRSKNUI.Module, NRSKNUI.AceEvent
---@class RangeChecker : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Skinning : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Tooltips : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Minimap : NRSKNUI.Module, NRSKNUI.AceEvent
---@class BurningRush : NRSKNUI.Module, NRSKNUI.AceEvent
---@class AuctionHouseFilter : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Automation : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceHook
---@class Tweaks : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceHook
---@class XPBar : NRSKNUI.Module, NRSKNUI.AceEvent
---@class CopyAnything : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Recuperate : NRSKNUI.Module, NRSKNUI.AceEvent
---@class MiscVars : NRSKNUI.Module, NRSKNUI.AceEvent
---@class Durability : NRSKNUI.Module, NRSKNUI.AceEvent
---@class CombatCross : NRSKNUI.Module, NRSKNUI.AceEvent
---@class CombatMessage : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceTimer
---@class CombatRes : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceTimer
---@class Restricted : NRSKNUI.Module, NRSKNUI.AceEvent
---@class CursorCircle : NRSKNUI.Module, NRSKNUI.AceEvent
---@class UnitFrames : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceTimer, NRSKNUI.AceHook
---@class PlayerAuras : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceTimer, NRSKNUI.AceHook
---@class AdvancedDebuffs : NRSKNUI.Module, NRSKNUI.AceEvent, NRSKNUI.AceTimer, NRSKNUI.AceHook

-- Typed accessors. Overloads dispatch on the literal module name.

---@type NRSKNUI
local NRSKNUI

--- Fetch a registered module by name.
---@overload fun(self: NRSKNUI, name: "CombatTimer", silent?: boolean): CombatTimer
---@overload fun(self: NRSKNUI, name: "Gateway", silent?: boolean): Gateway
---@overload fun(self: NRSKNUI, name: "PotionReady", silent?: boolean): PotionReady
---@overload fun(self: NRSKNUI, name: "RangeChecker", silent?: boolean): RangeChecker
---@overload fun(self: NRSKNUI, name: "Skinning", silent?: boolean): Skinning
---@overload fun(self: NRSKNUI, name: "Tooltips", silent?: boolean): Tooltips
---@overload fun(self: NRSKNUI, name: "Minimap", silent?: boolean): Minimap
---@overload fun(self: NRSKNUI, name: "BurningRush", silent?: boolean): BurningRush
---@overload fun(self: NRSKNUI, name: "AuctionHouseFilter", silent?: boolean): AuctionHouseFilter
---@overload fun(self: NRSKNUI, name: "Automation", silent?: boolean): Automation
---@overload fun(self: NRSKNUI, name: "Tweaks", silent?: boolean): Tweaks
---@overload fun(self: NRSKNUI, name: "XPBar", silent?: boolean): XPBar
---@overload fun(self: NRSKNUI, name: "CopyAnything", silent?: boolean): CopyAnything
---@overload fun(self: NRSKNUI, name: "Recuperate", silent?: boolean): Recuperate
---@overload fun(self: NRSKNUI, name: "MiscVars", silent?: boolean): MiscVars
---@overload fun(self: NRSKNUI, name: "Durability", silent?: boolean): Durability
---@overload fun(self: NRSKNUI, name: "CombatCross", silent?: boolean): CombatCross
---@overload fun(self: NRSKNUI, name: "CombatMessage", silent?: boolean): CombatMessage
---@overload fun(self: NRSKNUI, name: "CombatRes", silent?: boolean): CombatRes
---@overload fun(self: NRSKNUI, name: "Restricted", silent?: boolean): Restricted
---@overload fun(self: NRSKNUI, name: "CursorCircle", silent?: boolean): CursorCircle
---@overload fun(self: NRSKNUI, name: "UnitFrames", silent?: boolean): UnitFrames
---@overload fun(self: NRSKNUI, name: "PlayerAuras", silent?: boolean): PlayerAuras
---@overload fun(self: NRSKNUI, name: "AdvancedDebuffs", silent?: boolean): AdvancedDebuffs
---@param name string
---@param silent? boolean
---@return NRSKNUI.Module
function NRSKNUI:GetModule(name, silent) end

--- Register a new module. Trailing args are embedded library names (e.g. "AceEvent-3.0").
---@overload fun(self: NRSKNUI, name: "CombatTimer", ...: string): CombatTimer
---@overload fun(self: NRSKNUI, name: "Gateway", ...: string): Gateway
---@overload fun(self: NRSKNUI, name: "PotionReady", ...: string): PotionReady
---@overload fun(self: NRSKNUI, name: "RangeChecker", ...: string): RangeChecker
---@overload fun(self: NRSKNUI, name: "Skinning", ...: string): Skinning
---@overload fun(self: NRSKNUI, name: "Tooltips", ...: string): Tooltips
---@overload fun(self: NRSKNUI, name: "Minimap", ...: string): Minimap
---@overload fun(self: NRSKNUI, name: "BurningRush", ...: string): BurningRush
---@overload fun(self: NRSKNUI, name: "AuctionHouseFilter", ...: string): AuctionHouseFilter
---@overload fun(self: NRSKNUI, name: "Automation", ...: string): Automation
---@overload fun(self: NRSKNUI, name: "Tweaks", ...: string): Tweaks
---@overload fun(self: NRSKNUI, name: "XPBar", ...: string): XPBar
---@overload fun(self: NRSKNUI, name: "CopyAnything", ...: string): CopyAnything
---@overload fun(self: NRSKNUI, name: "Recuperate", ...: string): Recuperate
---@overload fun(self: NRSKNUI, name: "MiscVars", ...: string): MiscVars
---@overload fun(self: NRSKNUI, name: "Durability", ...: string): Durability
---@overload fun(self: NRSKNUI, name: "CombatCross", ...: string): CombatCross
---@overload fun(self: NRSKNUI, name: "CombatMessage", ...: string): CombatMessage
---@overload fun(self: NRSKNUI, name: "CombatRes", ...: string): CombatRes
---@overload fun(self: NRSKNUI, name: "Restricted", ...: string): Restricted
---@overload fun(self: NRSKNUI, name: "CursorCircle", ...: string): CursorCircle
---@overload fun(self: NRSKNUI, name: "UnitFrames", ...: string): UnitFrames
---@overload fun(self: NRSKNUI, name: "PlayerAuras", ...: string): PlayerAuras
---@overload fun(self: NRSKNUI, name: "AdvancedDebuffs", ...: string): AdvancedDebuffs
---@param name string
---@param ... string
---@return NRSKNUI.Module
function NRSKNUI:NewModule(name, ...) end
