---@meta

--- AceEvent-3.0 provides event registration and secure dispatching via CallbackHandler-1.0.
--- Embedded into a module by listing "AceEvent-3.0" in NRSKNUI:NewModule(...), which makes
--- these methods available directly on the module (self).
---@class NRSKNUI.AceEvent: NRSKNUI.Module
---
--- Register for a Blizzard event. `callback` may be a function or a method name on self;
--- if omitted it defaults to a method named after the event. An optional `arg` is passed
--- as the first argument to the callback (the event name follows).
---@field RegisterEvent fun(self: NRSKNUI.AceEvent, event: string, callback?: string|fun(event: string, ...: any), arg?: any)
---
--- Unregister a previously registered Blizzard event.
---@field UnregisterEvent fun(self: NRSKNUI.AceEvent, event: string)
---
--- Register for a custom AceEvent-internal message. Same callback/arg semantics as RegisterEvent.
---@field RegisterMessage fun(self: NRSKNUI.AceEvent, message: string, callback?: string|fun(message: string, ...: any), arg?: any)
---
--- Unregister a previously registered message.
---@field UnregisterMessage fun(self: NRSKNUI.AceEvent, message: string)
---
--- Send a message to other addons registered for it, passing along any extra arguments.
---@field SendMessage fun(self: NRSKNUI.AceEvent, message: string, ...: any)
